name: Build

on:
  #- push
  #- pull_request
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # TODO: compile check
      - name: Generate Changelog
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Get text after for this release from changelog files
          sed -n "/^##.*${{ github.ref_name }}.*$/,/^##/{/^##/d ; p}" CHANGELOG.md | sed -z "s/^\n*//g" - > ${{ github.workspace }}-CHANGELOG.txt
      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
 
# vim: ts=2 sw=2 et

